INSERT INTO map VALUES('Destruction_2x3_Montagne_1','Death Row','https://i.imgur.com/hrbEbod.png','Land',1);
INSERT INTO map VALUES('Destruction_3x3_Marine_3_Reduite_Terrestre','Hell in a very small place','https://i.imgur.com/KC9qkLa.png','Land',1);
INSERT INTO map VALUES('Destruction_2x3_Hwaseong','Nuclear winter is coming','https://i.imgur.com/ErH1aXW.png','Land',1);
INSERT INTO map VALUES('Destruction_2x3_Gangjin','Mud Fight','https://i.imgur.com/R6nGA3h.png','Land',1);
INSERT INTO map VALUES('Destruction_4x4_Marine_6','Out of the blue','https://i.imgur.com/cjoI4rU.png','Naval',1);
INSERT INTO map VALUES('Destruction_2x3_Tohoku_Alt','Paddy Field','https://i.imgur.com/eRObO0N.png','Land',1);
INSERT INTO map VALUES('Destruction_3x3_Muju','Plunjing Valley','https://i.imgur.com/M6VBoSf.png','Land',1);
INSERT INTO map VALUES('Destruction_3x3_Muju_Alt','Punchbowl','https://i.imgur.com/GZ04ix2.png','Land',1);
INSERT INTO map VALUES('Destruction_4x4_Marine_7','Standoff in Barents','https://i.imgur.com/GZmGguc.png','Naval',1);
INSERT INTO map VALUES('Destruction_5x3_Marine_1_small_Terrestre','Strait to the point','https://i.imgur.com/hZagcJG.png','Land',1);
INSERT INTO map VALUES('Destruction_2x3_Esashi','Tropic Thunder','https://i.imgur.com/bPGVczE.png','Land',1);
INSERT INTO map VALUES('Destruction_2x2_port_Wonsan_Terrestre','Wonsan Harbour','https://i.imgur.com/GpVdSrP.png','Land',1);
INSERT INTO map VALUES('Destruction_2x2_port_Wonsan','Wonsan Harbour','https://i.imgur.com/Wkz3xLO.png','Combined',1);
INSERT INTO map VALUES('Destruction_4x4_Marine_10','Alea Jacta West','https://i.imgur.com/cHgCBuQ.png','Naval',2);
INSERT INTO map VALUES('Destruction_3x3_Marine_3_Terrestre','Another D-Day in paradise','https://i.imgur.com/etC2ga1.png','Land',2);
INSERT INTO map VALUES('Destruction_2x3_Boseong','Apocalypse Imminent','https://i.imgur.com/891SJr3.png','Land',2);
INSERT INTO map VALUES('Destruction_4x4_Marine_9','Bulldogs and Vampires','https://i.imgur.com/gsVTISv.png','Naval',2);
INSERT INTO map VALUES('Destruction_3x2_Montagne_3','Chosin Reservoir','https://i.imgur.com/Rg8kL34.png','Land',2);
INSERT INTO map VALUES('Destruction_3x2_Haenam_Alt','Operation Chromite','https://i.imgur.com/Mipa7tr.png','Land',2);
INSERT INTO map VALUES('Destruction_3x2_Boryeong_Terrestre','Gunboat Diplomacy','https://i.imgur.com/avXaeoV.png','Land',2);
INSERT INTO map VALUES('Destruction_3x3_Highway_Small','Highway to Seoul','https://i.imgur.com/FeSieuO.png','Land',2);
INSERT INTO map VALUES('Destruction_2x3_Anbyon','Hop and Glory','https://i.imgur.com/YJFs3Gl.png','Land',2);
INSERT INTO map VALUES('Destruction_3x2_Taebuko','Jungle Law','https://i.imgur.com/W1vDPWl.png','Land',2);
INSERT INTO map VALUES('Destruction_2x3_Tohoku','Paddy Field','https://i.imgur.com/ppY1GmT.png','Land',2);
INSERT INTO map VALUES('Destruction_5x3_Marine_1_small','Strait to the point','https://i.imgur.com/2UIotC1.png','Combined',2);
INSERT INTO map VALUES('Destruction_3x3_Pyeongtaek_Alt','38th Perpendicular','https://i.imgur.com/nxpqthC.png','Land',3);
INSERT INTO map VALUES('Destruction_3x3_Marine_3','Another D-Day in paradise','https://i.imgur.com/UE8F6Fu.png','Combined',3);
INSERT INTO map VALUES('Destruction_4x4_Marine_4','Atoll Inbound','https://i.imgur.com/E0elnSW.png','Naval',3);
INSERT INTO map VALUES('Destruction_3x2_Haenam','Back to Inchon','https://i.imgur.com/mmHFg4f.png','Land',3);
INSERT INTO map VALUES('Destruction_3x2_Taean','Bloody Ridge','https://i.imgur.com/NqaDjKE.png','Land',3);
INSERT INTO map VALUES('Destruction_2x3_Montagne_2','Cliff Hanger','https://i.imgur.com/AXDjQuC.png','Land',3);
INSERT INTO map VALUES('Destruction_3x3_Thuringer_Wald_Alt','Crossroads','https://i.imgur.com/FeeYhNA.png','Land',3);
INSERT INTO map VALUES('Destruction_3x2_Boryeong','Gunboat diplomacy','https://i.imgur.com/TtFqNn4.png','Combined',3);
INSERT INTO map VALUES('Destruction_3x3_Highway','Highway To Seul','https://i.imgur.com/BA7HjeC.png','Land',3);
INSERT INTO map VALUES('Destruction_3x2_Sangju','Tough Jungle','https://i.imgur.com/JiQMETs.png','Land',3);
INSERT INTO map VALUES('Destruction_5x3_Marine_1_Terrestre','Strait to the point','https://i.imgur.com/Ad9RuDh.png','Land',3);
INSERT INTO map VALUES('Destruction_4x4_Marine_5','Waterworld','https://i.imgur.com/sCCQ0Rt.png','Naval',3);
INSERT INTO map VALUES('Destruction_Chongju_Alt','Wrecks and Rocks','https://i.imgur.com/EfsaFrb.png','Land',3);
INSERT INTO map VALUES('Destruction_3x3_Pyeongtaek','38th Parallel','https://i.imgur.com/GvNspyn.png','Land',4);
INSERT INTO map VALUES('Destruction_3x3_Montagne_4','A Maze in Japan','https://i.imgur.com/y4eAdO1.png','Land',4);
INSERT INTO map VALUES('Destruction_5x3_Marine_1_Alt','Battle of Yuchalnok Pass','https://i.imgur.com/XpynqGm.png','Land',4);
INSERT INTO map VALUES('Destruction_3x3_Montagne_1','Cold War Z','https://i.imgur.com/WQtXBsT.png','Land',4);
INSERT INTO map VALUES('Destruction_3x3_Asgard','Crown of Crags','https://i.imgur.com/oIRlXOn.png','Land',4);
INSERT INTO map VALUES('Destruction_4x4_ThreeMileIsland_Alt','Final Meltdown','https://i.imgur.com/4y6rXxl.png','Land',4);
INSERT INTO map VALUES('Destruction_3x3_Gangjin','Floods','https://i.imgur.com/tNtOowg.png','Land',4);
INSERT INTO map VALUES('Destruction_4x3_Gjoll','Heartbreak Ridge','https://i.imgur.com/pKDl1oS.png','Land',4);
INSERT INTO map VALUES('Destruction_3x3_Chongju','Korea Rocks','https://i.imgur.com/fSpBBzQ.png','Land',4);
INSERT INTO map VALUES('Destruction_3x3_Marine_2','Smoke in the water','https://i.imgur.com/xYew5Uy.png','Combined',4);
INSERT INTO map VALUES('Destruction_5x3_Marine_1','Strait to the point','https://i.imgur.com/r2HIKFL.png','Combined',4);
INSERT INTO map VALUES('Destruction_4x3_Sangju_Alt','The Green Mile','https://i.imgur.com/TxJgRWu.png','Land',4);
INSERT INTO map VALUES('Destruction_4x4_ThreeMileIsland','Three Mile Island','https://i.imgur.com/6KKYV7c.png','Land',4);
INSERT INTO map VALUES('Destruction_3x3_Thuringer_Wald','Thuringer Wald','https://i.imgur.com/mEYaAwp.png','Land',4);
INSERT INTO map VALUES('Destruction_5x3_Asgard_10v10','Asgard','https://i.imgur.com/3ELwr4U.png','Land',10);
INSERT INTO map VALUES('Destruction_5x3_Gjoll_10v10','Gjoll','https://i.imgur.com/chaYl2a.png','Land',10);
INSERT INTO map VALUES('Destruction_4x4_Russian_Roulette','Russian Roulette','https://i.imgur.com/GkuyFcF.png','Land',10);

INSERT INTO map VALUES('Conquete_2x3_Montagne_1','Death Row','https://i.imgur.com/EaQ3Xk3.png','Land',1);
INSERT INTO map VALUES('Conquete_3x3_Marine_3_Reduite_Terrestre','Hell in a very small place','https://i.imgur.com/V34OC4N.png','Land',1);
INSERT INTO map VALUES('Conquete_2x3_Hwaseong','Nuclear winter is coming','https://i.imgur.com/SCP7Rsc.png','Land',1);
INSERT INTO map VALUES('Conquete_2x3_Gangjin','Mud Fight','https://i.imgur.com/EBMdllK.png','Land',1);
INSERT INTO map VALUES('Conquete_4x4_Marine_6','Out of the blue','https://i.imgur.com/xfoz2K2.png','Naval',1);
INSERT INTO map VALUES('Conquete_2x3_Tohoku_Alt','Paddy Field','https://i.imgur.com/3VzfQB5.png','Land',1);
INSERT INTO map VALUES('Conquete_3x3_Muju','Plunjing Valley','https://i.imgur.com/qTSQexL.png','Land',1);
INSERT INTO map VALUES('Conquete_3x3_Muju_Alt','Punchbowl','https://i.imgur.com/TocvX3i.png','Land',1);
INSERT INTO map VALUES('Conquete_4x4_Marine_7','Standoff in Barents','https://i.imgur.com/ToIjdiw.png','Naval',1);
INSERT INTO map VALUES('Conquete_5x3_Marine_1_small_Terrestre','Strait to the point','https://i.imgur.com/YghehpZ.png','Land',1);
INSERT INTO map VALUES('Conquete_2x3_Esashi','Tropic Thunder','https://i.imgur.com/GbMOV64.png','Land',1);
INSERT INTO map VALUES('Conquete_2x2_port_Wonsan_Terrestre','Wonsan Harbour','https://i.imgur.com/0ZZ3zjX.png','Land',1);
INSERT INTO map VALUES('Conquete_2x2_port_Wonsan','Wonsan Harbour','https://i.imgur.com/5gsyw9G.png','Combined',1);
INSERT INTO map VALUES('Conquete_4x4_Marine_10','Alea Jacta West','https://i.imgur.com/BV0gmRK.png','Naval',2);
INSERT INTO map VALUES('Conquete_3x3_Marine_3_Terrestre','Another D-Day in paradise','https://i.imgur.com/YR2xt96.png','Land',2);
INSERT INTO map VALUES('Conquete_2x3_Boseong','Apocalypse Imminent','https://i.imgur.com/QvmlXWh.png','Land',2);
INSERT INTO map VALUES('Conquete_4x4_Marine_9','Bulldogs and Vampires','https://i.imgur.com/vDQATFo.png','Naval',2);
INSERT INTO map VALUES('Conquete_3x2_Montagne_3','Chosin Reservoir','https://i.imgur.com/lBFVCPk.png','Land',2);
INSERT INTO map VALUES('Conquete_3x2_Haenam_Alt','Operation Chromite','https://i.imgur.com/vf9EiRC.png','Land',2);
INSERT INTO map VALUES('Conquete_3x2_Boryeong_Terrestre','Gunboat Diplomacy','https://i.imgur.com/IpfCUn4.png','Land',2);
INSERT INTO map VALUES('Conquete_3x3_Highway_Small','Highway to Seoul','https://i.imgur.com/PBT1n57.png','Land',2);
INSERT INTO map VALUES('Conquete_2x3_Anbyon','Hop and Glory','https://i.imgur.com/CytqciN.png','Land',2);
INSERT INTO map VALUES('Conquete_3x2_Taebuko','Jungle Law','https://i.imgur.com/j9YrqfC.png','Land',2);
INSERT INTO map VALUES('Conquete_2x3_Tohoku','Paddy Field','https://i.imgur.com/NDzGgWi.png','Land',2);
INSERT INTO map VALUES('Conquete_5x3_Marine_1_small','Strait to the point','https://i.imgur.com/WeODb6l.png','Combined',2);
INSERT INTO map VALUES('Conquete_3x3_Pyeongtaek_Alt','38th Perpendicular','https://i.imgur.com/LLmMo06.png','Land',3);
INSERT INTO map VALUES('Conquete_3x3_Marine_3','Another D-Day in paradise','https://i.imgur.com/FxKw6sO.png','Combined',3);
INSERT INTO map VALUES('Conquete_4x4_Marine_4','Atoll Inbound','https://i.imgur.com/VKaAxpd.png','Naval',3);
INSERT INTO map VALUES('Conquete_3x2_Haenam','Back to Inchon','https://i.imgur.com/wq2f5rl.png','Land',3);
INSERT INTO map VALUES('Conquete_3x2_Taean','Bloody Ridge','https://i.imgur.com/rZxBl3x.png','Land',3);
INSERT INTO map VALUES('Conquete_2x3_Montagne_2','Cliff Hanger','https://i.imgur.com/yZi2xfB.png','Land',3);
INSERT INTO map VALUES('Conquete_3x3_Thuringer_Wald_Alt','Crossroads','https://i.imgur.com/HREblHE.png','Land',3);
INSERT INTO map VALUES('Conquete_3x2_Boryeong','Gunboat diplomacy','https://i.imgur.com/COe0dUk.png','Combined',3);
INSERT INTO map VALUES('Conquete_3x3_Highway','Highway To Seul','https://i.imgur.com/iH45wWa.png','Land',3);
INSERT INTO map VALUES('Conquete_3x2_Sangju','Tough Jungle','https://i.imgur.com/0kA3HfE.png','Land',3);
INSERT INTO map VALUES('Conquete_5x3_Marine_1_Terrestre','Strait to the point','https://i.imgur.com/YtABNJv.png','Land',3);
INSERT INTO map VALUES('Conquete_4x4_Marine_5','Waterworld','https://i.imgur.com/W4OvRT6.png','Naval',3);
INSERT INTO map VALUES('Conquete_Chongju_Alt','Wrecks and Rocks','https://i.imgur.com/fCHRsO5.png','Land',3);
INSERT INTO map VALUES('Conquete_3x3_Pyeongtaek','38th Parallel','https://i.imgur.com/GDCvTKZ.png','Land',4);
INSERT INTO map VALUES('Conquete_3x3_Montagne_4','A Maze in Japan','https://i.imgur.com/wt3EuXM.png','Land',4);
INSERT INTO map VALUES('Conquete_5x3_Marine_1_Alt','Battle of Yuchalnok Pass','https://i.imgur.com/5eK811X.png','Land',4);
INSERT INTO map VALUES('Conquete_3x3_Montagne_1','Cold War Z','https://i.imgur.com/nDwQdYY.png','Land',4);
INSERT INTO map VALUES('Conquete_3x3_Asgard','Crown of Crags','https://i.imgur.com/SAgtSct.png','Land',4);
INSERT INTO map VALUES('Conquete_4x4_ThreeMileIsland_Alt','Final Meltdown','https://i.imgur.com/JLSnoTr.png','Land',4);
INSERT INTO map VALUES('Conquete_3x3_Gangjin','Floods','https://i.imgur.com/hBdY6qe.png','Land',4);
INSERT INTO map VALUES('Conquete_4x3_Gjoll','Heartbreak Ridge','https://i.imgur.com/d6FNyGX.png','Land',4);
INSERT INTO map VALUES('Conquete_3x3_Chongju','Korea Rocks','https://i.imgur.com/NpVTflB.png','Land',4);
INSERT INTO map VALUES('Conquete_3x3_Marine_2','Smoke in the water','https://i.imgur.com/mfkAF2x.png','Combined',4);
INSERT INTO map VALUES('Conquete_5x3_Marine_1','Strait to the point','https://i.imgur.com/uzJMkCD.png','Combined',4);
INSERT INTO map VALUES('Conquete_4x3_Sangju_Alt','The Green Mile','https://i.imgur.com/Pet8LEm.png','Land',4);
INSERT INTO map VALUES('Conquete_4x4_ThreeMileIsland','Three Mile Island','https://i.imgur.com/GqO6xsf.png','Land',4);
INSERT INTO map VALUES('Conquete_3x3_Thuringer_Wald','Thuringer Wald','https://i.imgur.com/lrm3WIy.png','Land',4);
INSERT INTO map VALUES('Conquete_5x3_Asgard_10v10','Asgard','https://i.imgur.com/cRseREr.png','Land',10);
INSERT INTO map VALUES('Conquete_5x3_Gjoll_10v10','Gjoll','https://i.imgur.com/yg2cL1M.png','Land',10);
INSERT INTO map VALUES('Conquete_4x4_Russian_Roulette','Russian Roulette','https://i.imgur.com/FVYV0y8.png','Land',10);
