INSERT INTO map VALUES('Destruction_2x3_Montagne_1','Death Row','https://i.imgur.com/zD8DxOR.jpg','Ground',1);
INSERT INTO map VALUES('Destruction_3x3_Marine_3_Reduite_Terrestre','Hell in a very small place','https://i.imgur.com/1h8Subh.jpg','Ground',1);
INSERT INTO map VALUES('Destruction_2x3_Hwaseong','Nuclear winter is coming','https://i.imgur.com/RDodCEc.jpg','Ground',1);
INSERT INTO map VALUES('Destruction_2x3_Gangjin','Mud Fight','https://i.imgur.com/zXnEn6s.jpg','Ground',1);
INSERT INTO map VALUES('Destruction_4x4_Marine_6','Out of the blue',NULL,'Naval',1);
INSERT INTO map VALUES('Destruction_2x3_Tohoku_Alt','Paddy Field','https://i.imgur.com/AU2q1mm.jpg','Ground',1);
INSERT INTO map VALUES('Destruction_3x3_Muju','Plunjing Valley','https://i.imgur.com/SI3AaLG.jpg','Ground',1);
INSERT INTO map VALUES('Destruction_3x3_Muju_Alt','Punchbowl','https://i.imgur.com/tkzeccS.jpg','Ground',1);
INSERT INTO map VALUES('Destruction_4x4_Marine_7','Standoff in Barents',NULL,'Naval',1);
INSERT INTO map VALUES('Destruction_5x3_Marine_1_small_Terrestre','Strait to the point','https://i.imgur.com/Cfho2Yp.jpg','Ground',1);
INSERT INTO map VALUES('Destruction_2x3_Esashi','Tropic Thunder','https://i.imgur.com/RFzxsJz.jpg','Ground',1);
INSERT INTO map VALUES('Destruction_2x2_port_Wonsan_Terrestre','Wonsan Harbour','https://i.imgur.com/s2YQxx1.jpg','Ground',1);
INSERT INTO map VALUES('Destruction_2x2_port_Wonsan','Wonsan Harbour','https://i.imgur.com/qsuGEAG.jpg','Combined',1);
INSERT INTO map VALUES('Destruction_4x4_Marine_10','Alea Jacta West',NULL,'Naval',2);
INSERT INTO map VALUES('Destruction_3x3_Marine_3_Terrestre','Another D-Day in paradise','https://i.imgur.com/GR3bukQ.jpg','Ground',2);
INSERT INTO map VALUES('Destruction_2x3_Boseong','Apocalypse Imminent','https://i.imgur.com/cvdOsNb.jpg','Ground',2);
INSERT INTO map VALUES('Destruction_4x4_Marine_9','Bulldogs and Vampires',NULL,'Naval',2);
INSERT INTO map VALUES('Destruction_3x2_Montagne_3','Chosin Reservoir','https://i.imgur.com/l8NYcPn.jpg','Ground',2);
INSERT INTO map VALUES('Destruction_3x2_Haenam_Alt','Operation Chromite','https://i.imgur.com/CsymC2U.jpg','Ground',2);
INSERT INTO map VALUES('Destruction_3x2_Boryeong_Terrestre','Gunboat Diplomacy','https://i.imgur.com/E9tr7FL.jpg','Ground',2);
INSERT INTO map VALUES('Destruction_3x3_Highway_Small','Highway to Seoul','https://i.imgur.com/M5dLnwd.jpg','Ground',2);
INSERT INTO map VALUES('Destruction_2x3_Anbyon','Hop and Glory','https://i.imgur.com/tD3KkQs.jpg','Ground',2);
INSERT INTO map VALUES('Destruction_3x2_Taebuko','Jungle Law','https://i.imgur.com/oUPvXa7.jpg','Ground',2);
INSERT INTO map VALUES('Destruction_2x3_Tohoku','Paddy Field','https://i.imgur.com/QgJMZYh.jpg','Ground',2);
INSERT INTO map VALUES('Destruction_5x3_Marine_1_small','Strait to the point',NULL,'Combined',2);
INSERT INTO map VALUES('Destruction_3x3_Pyeongtaek_Alt','38th Perpendicular',NULL,'Ground',3);
INSERT INTO map VALUES('Destruction_3x3_Marine_3','Another D-Day in paradise','https://i.imgur.com/ehmtpEa.jpg','Combined',3);
INSERT INTO map VALUES('Destruction_4x4_Marine_4','Atoll Inbound',NULL,'Naval',3);
INSERT INTO map VALUES('Destruction_3x2_Haenam','Back to Inchon','https://i.imgur.com/OIIS9rF.jpg','Ground',3);
INSERT INTO map VALUES('Destruction_3x2_Taean','Bloody Ridge','https://i.imgur.com/724pMZK.jpg','Ground',3);
INSERT INTO map VALUES('Destruction_2x3_Montagne_2','Cliff Hanger','https://i.imgur.com/ZB6XA0e.jpg','Ground',3);
INSERT INTO map VALUES('Destruction_3x3_Thuringer_Wald_Alt','Crossroads',NULL,'Ground',3);
INSERT INTO map VALUES('Destruction_3x2_Boryeong','Gunboat diplomacy','https://i.imgur.com/nz0b6hP.jpg','Combined',3);
INSERT INTO map VALUES('Destruction_3x3_Highway','Highway To Seul',NULL,'Ground',3);
INSERT INTO map VALUES('Destruction_3x2_Sangju','Tough Jungle','https://i.imgur.com/SCKENgp.jpg','Ground',3);
INSERT INTO map VALUES('Destruction_5x3_Marine_1_Terrestre','Strait to the point',NULL,'Ground',3);
INSERT INTO map VALUES('Destruction_4x4_Marine_5','Waterworld',NULL,'Naval',3);
INSERT INTO map VALUES('Destruction_Chongju_Alt','Wrecks and Rocks','https://i.imgur.com/68LkGAp.jpg','Ground',3);
INSERT INTO map VALUES('Destruction_3x3_Pyeongtaek','38th Parallel',NULL,'Ground',4);
INSERT INTO map VALUES('Destruction_3x3_Montagne_4','A Maze in Japan',NULL,'Ground',4);
INSERT INTO map VALUES('Destruction_5x3_Marine_1_Alt','Battle of Yuchalnok Pass',NULL,'Ground',4);
INSERT INTO map VALUES('Destruction_3x3_Montagne_1','Cold War Z',NULL,'Ground',4);
INSERT INTO map VALUES('Destruction_3x3_Asgard','Crown of Crags',NULL,'Ground',4);
INSERT INTO map VALUES('Destruction_4x4_ThreeMileIsland_Alt','Final Meltdown',NULL,'Ground',4);
INSERT INTO map VALUES('Destruction_3x3_Gangjin','Floods',NULL,'Ground',4);
INSERT INTO map VALUES('Destruction_4x3_Gjoll','Heartbreak Ridge',NULL,'Ground',4);
INSERT INTO map VALUES('Destruction_3x3_Chongju','Korea Rocks',NULL,'Ground',4);
INSERT INTO map VALUES('Destruction_3x3_Marine_2','Smoke in the water',NULL,'Combined',4);
INSERT INTO map VALUES('Destruction_5x3_Marine_1','Strait to the point',NULL,'Combined',4);
INSERT INTO map VALUES('Destruction_4x3_Sangju_Alt','The Green Mile',NULL,'Ground',4);
INSERT INTO map VALUES('Destruction_4x4_ThreeMileIsland','Three Mile Island',NULL,'Ground',4);
INSERT INTO map VALUES('Destruction_3x3_Thuringer_Wald','Thuringer Wald',NULL,'Ground',4);
INSERT INTO map VALUES('Destruction_5x3_Asgard_10v10','Asgard',NULL,'Ground',10);
INSERT INTO map VALUES('Destruction_5x3_Gjoll_10v10','Gjoll',NULL,'Ground',10);
INSERT INTO map VALUES('Destruction_4x4_Russian_Roulette','Russian Roulette',NULL,'Ground',10);

INSERT INTO map VALUES('Conquete_2x3_Montagne_1','Death Row','https://i.imgur.com/zD8DxOR.jpg','Ground',1);
INSERT INTO map VALUES('Conquete_3x3_Marine_3_Reduite_Terrestre','Hell in a very small place','https://i.imgur.com/1h8Subh.jpg','Ground',1);
INSERT INTO map VALUES('Conquete_2x3_Hwaseong','Nuclear winter is coming','https://i.imgur.com/RDodCEc.jpg','Ground',1);
INSERT INTO map VALUES('Conquete_2x3_Gangjin','Mud Fight','https://i.imgur.com/zXnEn6s.jpg','Ground',1);
INSERT INTO map VALUES('Conquete_4x4_Marine_6','Out of the blue',NULL,'Naval',1);
INSERT INTO map VALUES('Conquete_2x3_Tohoku_Alt','Paddy Field','https://i.imgur.com/AU2q1mm.jpg','Ground',1);
INSERT INTO map VALUES('Conquete_3x3_Muju','Plunjing Valley','https://i.imgur.com/SI3AaLG.jpg','Ground',1);
INSERT INTO map VALUES('Conquete_3x3_Muju_Alt','Punchbowl','https://i.imgur.com/tkzeccS.jpg','Ground',1);
INSERT INTO map VALUES('Conquete_4x4_Marine_7','Standoff in Barents',NULL,'Naval',1);
INSERT INTO map VALUES('Conquete_5x3_Marine_1_small_Terrestre','Strait to the point','https://i.imgur.com/Cfho2Yp.jpg','Ground',1);
INSERT INTO map VALUES('Conquete_2x3_Esashi','Tropic Thunder','https://i.imgur.com/RFzxsJz.jpg','Ground',1);
INSERT INTO map VALUES('Conquete_2x2_port_Wonsan_Terrestre','Wonsan Harbour','https://i.imgur.com/s2YQxx1.jpg','Ground',1);
INSERT INTO map VALUES('Conquete_2x2_port_Wonsan','Wonsan Harbour','https://i.imgur.com/qsuGEAG.jpg','Combined',1);
INSERT INTO map VALUES('Conquete_4x4_Marine_10','Alea Jacta West',NULL,'Naval',2);
INSERT INTO map VALUES('Conquete_3x3_Marine_3_Terrestre','Another D-Day in paradise','https://i.imgur.com/GR3bukQ.jpg','Ground',2);
INSERT INTO map VALUES('Conquete_2x3_Boseong','Apocalypse Imminent','https://i.imgur.com/cvdOsNb.jpg','Ground',2);
INSERT INTO map VALUES('Conquete_4x4_Marine_9','Bulldogs and Vampires',NULL,'Naval',2);
INSERT INTO map VALUES('Conquete_3x2_Montagne_3','Chosin Reservoir','https://i.imgur.com/l8NYcPn.jpg','Ground',2);
INSERT INTO map VALUES('Conquete_3x2_Haenam_Alt','Operation Chromite','https://i.imgur.com/CsymC2U.jpg','Ground',2);
INSERT INTO map VALUES('Conquete_3x2_Boryeong_Terrestre','Gunboat Diplomacy','https://i.imgur.com/E9tr7FL.jpg','Ground',2);
INSERT INTO map VALUES('Conquete_3x3_Highway_Small','Highway to Seoul','https://i.imgur.com/M5dLnwd.jpg','Ground',2);
INSERT INTO map VALUES('Conquete_2x3_Anbyon','Hop and Glory','https://i.imgur.com/tD3KkQs.jpg','Ground',2);
INSERT INTO map VALUES('Conquete_3x2_Taebuko','Jungle Law','https://i.imgur.com/oUPvXa7.jpg','Ground',2);
INSERT INTO map VALUES('Conquete_2x3_Tohoku','Paddy Field','https://i.imgur.com/QgJMZYh.jpg','Ground',2);
INSERT INTO map VALUES('Conquete_5x3_Marine_1_small','Strait to the point',NULL,'Combined',2);
INSERT INTO map VALUES('Conquete_3x3_Pyeongtaek_Alt','38th Perpendicular',NULL,'Ground',3);
INSERT INTO map VALUES('Conquete_3x3_Marine_3','Another D-Day in paradise','https://i.imgur.com/ehmtpEa.jpg','Combined',3);
INSERT INTO map VALUES('Conquete_4x4_Marine_4','Atoll Inbound',NULL,'Naval',3);
INSERT INTO map VALUES('Conquete_3x2_Haenam','Back to Inchon','https://i.imgur.com/OIIS9rF.jpg','Ground',3);
INSERT INTO map VALUES('Conquete_3x2_Taean','Bloody Ridge','https://i.imgur.com/724pMZK.jpg','Ground',3);
INSERT INTO map VALUES('Conquete_2x3_Montagne_2','Cliff Hanger','https://i.imgur.com/ZB6XA0e.jpg','Ground',3);
INSERT INTO map VALUES('Conquete_3x3_Thuringer_Wald_Alt','Crossroads',NULL,'Ground',3);
INSERT INTO map VALUES('Conquete_3x2_Boryeong','Gunboat diplomacy','https://i.imgur.com/nz0b6hP.jpg','Combined',3);
INSERT INTO map VALUES('Conquete_3x3_Highway','Highway To Seul',NULL,'Ground',3);
INSERT INTO map VALUES('Conquete_3x2_Sangju','Tough Jungle','https://i.imgur.com/SCKENgp.jpg','Ground',3);
INSERT INTO map VALUES('Conquete_5x3_Marine_1_Terrestre','Strait to the point',NULL,'Ground',3);
INSERT INTO map VALUES('Conquete_4x4_Marine_5','Waterworld',NULL,'Naval',3);
INSERT INTO map VALUES('Conquete_Chongju_Alt','Wrecks and Rocks','https://i.imgur.com/68LkGAp.jpg','Ground',3);
INSERT INTO map VALUES('Conquete_3x3_Pyeongtaek','38th Parallel',NULL,'Ground',4);
INSERT INTO map VALUES('Conquete_3x3_Montagne_4','A Maze in Japan',NULL,'Ground',4);
INSERT INTO map VALUES('Conquete_5x3_Marine_1_Alt','Battle of Yuchalnok Pass',NULL,'Ground',4);
INSERT INTO map VALUES('Conquete_3x3_Montagne_1','Cold War Z',NULL,'Ground',4);
INSERT INTO map VALUES('Conquete_3x3_Asgard','Crown of Crags',NULL,'Ground',4);
INSERT INTO map VALUES('Conquete_4x4_ThreeMileIsland_Alt','Final Meltdown',NULL,'Ground',4);
INSERT INTO map VALUES('Conquete_3x3_Gangjin','Floods',NULL,'Ground',4);
INSERT INTO map VALUES('Conquete_4x3_Gjoll','Heartbreak Ridge',NULL,'Ground',4);
INSERT INTO map VALUES('Conquete_3x3_Chongju','Korea Rocks',NULL,'Ground',4);
INSERT INTO map VALUES('Conquete_3x3_Marine_2','Smoke in the water',NULL,'Combined',4);
INSERT INTO map VALUES('Conquete_5x3_Marine_1','Strait to the point',NULL,'Combined',4);
INSERT INTO map VALUES('Conquete_4x3_Sangju_Alt','The Green Mile',NULL,'Ground',4);
INSERT INTO map VALUES('Conquete_4x4_ThreeMileIsland','Three Mile Island',NULL,'Ground',4);
INSERT INTO map VALUES('Conquete_3x3_Thuringer_Wald','Thuringer Wald',NULL,'Ground',4);
INSERT INTO map VALUES('Conquete_5x3_Asgard_10v10','Asgard',NULL,'Ground',10);
INSERT INTO map VALUES('Conquete_5x3_Gjoll_10v10','Gjoll',NULL,'Ground',10);
INSERT INTO map VALUES('Conquete_4x4_Russian_Roulette','Russian Roulette',NULL,'Ground',10);
